function plot_piecewise_intensities(intensities_approx,intensities_exact,intensities_JT)
% Plot of the approximated, exact and JT intensities

syms x
y1 = piecewise(0 < x < 1,intensities_approx(1),...
              1 < x < 2,intensities_approx(2),...
              2 < x < 3,intensities_approx(3),...
              3 < x < 4,intensities_approx(4),...
              4 < x < 5,intensities_approx(5),...
              5 < x < 6,intensities_approx(6),...
              6 < x < 7,intensities_approx(7));
y2 = piecewise(0 < x < 1,intensities_exact(1),...
              1 < x < 2,intensities_exact(2),...
              2 < x < 3,intensities_exact(3),...
              3 < x < 4,intensities_exact(4),...
              4 < x < 5,intensities_exact(5),...
              5 < x < 6,intensities_exact(6),...
              6 < x < 7,intensities_exact(7));
y3 = piecewise(0 < x < 1,intensities_JT(1),...
              1 < x < 2,intensities_JT(2),...
              2 < x < 3,intensities_JT(3),...
              3 < x < 4,intensities_JT(4),...
              4 < x < 5,intensities_JT(5),...
              5 < x < 6,intensities_JT(6),...
              6 < x < 7,intensities_JT(7));
figure(1)
fplot(y1)
hold on
fplot(y2)
fplot(y3)
xlabel('Time')
ylabel('Intensities [bps]')
legend('Approximated intensities','Exact intensities','JT intensities','Location','southeast')
hold off